export const GENERATE_VERIFICATION_CODE_SUCCESS = "GENERATE_VERIFICATION_CODE_SUCCESS";
export const GENERATE_VERIFICATION_CODE_FAIL = "GENERATE_VERIFICATION_CODE_FAIL";
export const GENERATE_VERIFICATION_CODE_REQUEST = "GENERATE_VERIFICATION_CODE_REQUEST";

export const GET_VERIFICATION_CODE_SUCCESS = "GET_VERIFICATION_CODE_SUCCESS";
export const GET_VERIFICATION_CODE_FAIL = "GET_VERIFICATION_CODE_FAIL";
export const GET_VERIFICATION_CODE_REQUEST = "GET_VERIFICATION_CODE_REQUEST";