export const ALL_PLAYERS_GET_SUCCESS = "ALL_PLAYERS_GET_SUCCESS";
export const ALL_PLAYERS_GET_FAIL = "ALL_PLAYERS_GET_FAIL";
export const ALL_PLAYERS_GET_REQUEST = "ALL_PLAYERS_GET_REQUEST";

export const PLAYER_GET_SUCCESS = "PLAYER_GET_SUCCESS";
export const PLAYER_GET_FAIL = "PLAYER_GET_FAIL";
export const PLAYER_GET_REQUEST = "PLAYER_GET_REQUEST";

export const PLAYER_SEARCH_SUCCESS = "PLAYER_SEARCH_SUCCESS";
export const PLAYER_SEARCH_FAIL = "PLAYER_SEARCH_FAIL";
export const PLAYER_SEARCH_REQUEST = "PLAYER_SEARCH_REQUEST";
