export const ALL_PLAYERS_GET_SUCCESS = "ALL_PLAYERS_GET_SUCCESS";
export const ALL_PLAYERS_GET_FAIL = "ALL_PLAYERS_GET_FAIL";
export const ALL_PLAYERS_GET_REQUEST = "ALL_PLAYERS_GET_REQUEST";

export const PLAYER_GET_SUCCESS = "PLAYER_GET_SUCCESS";
export const PLAYER_GET_FAIL = "PLAYER_GET_FAIL";
export const PLAYER_GET_REQUEST = "PLAYER_GET_REQUEST";

export const PLAYER_SEARCH_SUCCESS = "PLAYER_SEARCH_SUCCESS";
export const PLAYER_SEARCH_FAIL = "PLAYER_SEARCH_FAIL";
export const PLAYER_SEARCH_REQUEST = "PLAYER_SEARCH_REQUEST";

export const CHANGE_REQUEST_SUCCESS = "CHANGE_REQUEST_SUCCESS";
export const CHANGE_REQUEST_FAIL = "CHANGE_REQUEST_FAIL";
export const CHANGE_REQUEST_REQUEST = "CHANGE_REQUEST_REQUEST";

export const GET_CHANGE_REQUESTS_SUCCESS = "GET_CHANGE_REQUESTS_SUCCESS";
export const GET_CHANGE_REQUESTS_FAIL = "GET_CHANGE_REQUESTS_FAIL";
export const GET_CHANGE_REQUESTS_REQUEST = "GET_CHANGE_REQUESTS_REQUEST";

export const REMOVE_CHANGE_REQUEST_SUCCESS = "REMOVE_CHANGE_REQUEST_SUCCESS";
export const REMOVE_CHANGE_REQUEST_FAIL = "REMOVE_CHANGE_REQUEST_FAIL";
export const REMOVE_CHANGE_REQUEST_REQUEST = "REMOVE_CHANGE_REQUEST_REQUEST";


