export const ALL_POSTS_GET_SUCCESS = "ALL_POSTS_GET_SUCCESS";
export const ALL_POSTS_GET_FAIL = "ALL_POSTS_GET_FAIL";
export const ALL_POSTS_GET_REQUEST = "ALL_POSTS_GET_REQUEST";

export const POST_GET_SUCCESS = "POST_GET_SUCCESS";
export const POST_GET_FAIL = "POST_GET_FAIL";
export const POST_GET_REQUEST = "POST_GET_REQUEST";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";

export const POST_GETLIKES_REQUEST = "POST_GETLIKESE_REQUEST";
export const POST_GETLIKES_SUCCESS = "POST_GETLIKES_SUCCESS";
export const POST_GETLIKES_FAIL = "POST_GETLIKES_FAIL";

export const ALL_POSTS_SUCCESS = "ALL_POSTS_SUCCESS";
export const ALL_POSTS_FAIL = "ALL_POSTS_FAIL";
