export const ALL_REPORTS_GET_SUCCESS = "ALL_REPORTS_GET_SUCCESS";
export const ALL_REPORTS_GET_FAIL = "ALL_REPORTS_GET_FAIL";
export const ALL_REPORTS_GET_REQUEST = "ALL_REPORTS_GET_REQUEST";

export const REPORT_GET_SUCCESS = "REPORT_GET_SUCCESS";
export const REPORT_GET_FAIL = "REPORT_GET_FAIL";
export const REPORT_GET_REQUEST = "REPORT_GET_REQUEST";

export const REPORT_CREATE_REQUEST = "REPORT_CREATE_REQUEST";
export const REPORT_CREATE_SUCCESS = "REPORT_CREATE_SUCCESS";
export const REPORT_CREATE_FAIL = "REPORT_CREATE_FAIL";

export const REPORT_GETRESPONSE_REQUEST = "REPORT_GETRESPONSEE_REQUEST";
export const REPORT_GETRESPONSE_SUCCESS = "REPORT_GETRESPONSE_SUCCESS";
export const REPORT_GETRESPONSE_FAIL = "REPORT_GETRESPONSE_FAIL";

export const ALL_REPORTS_SUCCESS = "ALL_REPORTS_SUCCESS";
export const ALL_REPORTS_FAIL = "ALL_REPORTS_FAIL";

export const ALL_REPORTS_REQUEST = "ALL_REPORTS_REQUEST";