export const ALL_TEAMS_GET_SUCCESS = "ALL_TEAMS_GET_SUCCESS";
export const ALL_TEAMS_GET_FAIL = "ALL_TEAMS_GET_FAIL";
export const ALL_TEAMS_GET_REQUEST = "ALL_TEAMS_GET_REQUEST";

export const TEAM_GET_SUCCESS = "TEAM_GET_SUCCESS";
export const TEAM_GET_FAIL = "TEAM_GET_FAIL";
export const TEAM_GET_REQUEST = "TEAM_GET_REQUEST";