export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const ADMIN_VERIFICATION_REQUEST_SUCCESS = "ADMIN_VERIFICATION_REQUEST_SUCCESS";
export const ADMIN_VERIFICATION_REQUEST_FAIL = "ADMIN_VERIFICATION_REQUEST_FAIL";

export const INBOX_AFTER_DELETION_SUCCESS = "INBOX_AFTER_DELETION_SUCCESS" ;
export const VERIFICATION_STATUS_UPDATE = "VERIFICATION_STATUS_UPDATE";

export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";