import { v4 as uuid } from "uuid";

export const players = [
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
    playerImage: "531110_01.jpg",
  },
  {
    id: uuid(),
    name: "İsmail Yüksek",
    club: "Fenerbahçe",
    position: "Midfielder",
    bday: "26.01.1999",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Ferdi Kadıoğlu",
    club: "Fenerbahçe",
    position: "Midfielderr",
    bday: "07.10.1999",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Joshua King",
    club: "Fenerbahçe",
    position: "Striker",
    bday: "15.01.1992",
    nationality: "Norway",
  },
  {
    id: uuid(),
    name: "Altay Bayındır",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "14.04.1998",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.04.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.0.4.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.0.4.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.0.4.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.0.4.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.0.4.2003",
    nationality: "Turkey",
  },
  {
    id: uuid(),
    name: "Osman Ertuğrul Çetin",
    club: "Fenerbahçe",
    position: "Goal Keeper",
    bday: "20.0.4.2003",
    nationality: "Turkey",
  },
];
